[versions]
commons-codec = "1.18.0"
commons-collections4 = "4.5.0"
commons-lang3 = "3.17.0"
equalsverifier = "3.19.3"
hamcrest = "3.0"
jgrapht = "1.5.2"
junit5 = "5.12.2"
kotlin-jvm = "2.1.20"
kotlinx-coroutines = "1.10.2"
sonarqube-plugin = "6.2.0.5505"
struts2 = "7.0.3"

[libraries]
commons-codec = { group = "commons-codec", name = "commons-codec", version.ref = "commons-codec" }
commons-collections4 = { group = "org.apache.commons", name = "commons-collections4", version.ref = "commons-collections4" }
commons-lang3 = { group = "org.apache.commons", name = "commons-lang3", version.ref = "commons-lang3" }
equalsverifier = { group = "nl.jqno.equalsverifier", name = "equalsverifier", version.ref = "equalsverifier" }
hamcrest = { group = "org.hamcrest", name = "hamcrest", version.ref = "hamcrest" }
jgrapht-core = { group = "org.jgrapht", name = "jgrapht-core", version.ref = "jgrapht" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit5" }
kotlinx-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
struts2-core = { group = "org.apache.struts", name = "struts2-core", version.ref = "struts2" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-jvm" }
sonarqube-plugin = { id = "org.sonarqube", version.ref = "sonarqube-plugin" }
